### ISSUE TITLE
Can't initialize Client() anymore

### ISSUE THREAD

**Issue by JVT038** [wasi-master/sponsorblock.py#3]
After updating to 0.2.0, I can't initialize Sponsorblock Client anymore.
```python
Python 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sponsorblock
>>> client = sponsorblock.Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\sponsorblock\utils.py", line 124, in __call__
    if cls not in cls._instances:
AttributeError: type object 'Client' has no attribute '_instances'
```

**Comment by wasi-master** [comment]
Oh then I've made a mistake somewhere, I'll get on to fixing it

**Comment by JVT038** [comment]
Alright. I've temporarily downgraded to 0.1.0, let me know when you fix it, so I can upgrade to the newest version again

**Comment by wasi-master** [comment]
@JVT038 I've fixed it, update to 0.2.1

**Comment by JVT038** [comment]
Thanks for the quick fix :)

**Comment by wasi-master** [comment]
:)
